---
- name: Install Ingress NGINX using kubectl
  hosts: kubernetes_master
  become: yes
  tasks:
    - name: Apply Ingress NGINX manifest
      command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/cloud/deploy.yaml
      args:
        creates: /tmp/ingress-installed  # опционально, чтобы не выполнять повторно

    - name: Wait for ingress-nginx namespace to be created
      command: kubectl get namespace ingress-nginx
      register: namespace_check
      until: namespace_check.rc == 0
      retries: 10
      delay: 3
      ignore_errors: yes

#    - name: Wait for Ingress controller pods to be running
#      command: >
#        kubectl get pods -n ingress-nginx
#        -l app.kubernetes.io/name=ingress-nginx
#        -o jsonpath='{.items[*].status.phase}' | grep -q Running
 #     register: pods_check
#      until: pods_check.rc == 0
#      retries: 10
#      delay: 10
#      ignore_errors: yes

    - name: Display success message
      debug:
        msg: "Ingress NGINX controller successfully installed and running"
