- name: Prepare system for Kubernetes
  hosts: cluster_k8s                                #Будут использованы хосты из группы cluster_k8s
  become: yes
  tasks:
    - name: Load kernel modules                      #Загрузка модулей ядра через конфигурационный файл
      copy:
        dest: /etc/modules-load.d/k8s.conf           #Путь к файлу конфигурации k8s
        content: |
          overlay                                    #Модуль для overlay-файловых систем (требуется для container runtimes)
          br_netfilter                               #Модуль для фильтрации сетевого трафика на bridge-интерфейсах

    - name: Load modules immediately                 #Загружаем модули ядра из цикла
      command: modprobe {{ item }}
      loop:                                          #Цикл для загрузки модулей из списка
        - overlay
        - br_netfilter

    - name: Configure kernel parameters              #Настройка параметров ядра Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf                 #Сам файл конфигурации
        content: |                                   #Параметры которые вписываются
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl settings                    #Применяем изменённые параметры ядра
      command: sysctl --system

 #   - name: Reboot host                              #Перезагрузка хостов
  #    ansible.builtin.reboot:
   #     msg: "reboot Start"                            #Выводим информацию о перезагрузке на хосте
    #    connect_timeout: 5                             #Через 5 секунд начинаем перезагрузку и каждые 5 секунд проверяем достпуность хоста, общее время ожидания 600 секунд.
     #   reboot_timeout: 600
      #  pre_reboot_delay: 5
       # post_reboot_delay: 30                          #Задержка перед првоеркой доступности 30 секунд, после перезагрузки
#
 #   - name: Power on host
  #    wait_for_connection:                             #Ожидание доступности хоста после перезагрузки
   #     delay: 10
    #    timeout: 300
